### ISSUE TITLE
Advanced Scenarios > High-Performance Database Engine lists client libs

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#111]
**Which documentation does this apply to?**
User's Guide

Advanced Scenarios > High-Performance Database Engine lists Boost.Redis and Boost.MySQL, but these are client libraries - they are used from within the client program to interact with a server that is already built. These make sense for a HTTP server, but not for a database engine.

**Comment by PeterTurcan** [comment]
done
