### ISSUE TITLE
Common Scenarios > Networking improvement suggestions

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#113]
Applies to User Guide.

* Having Boost.Thread, Boost.SmartPtr and Boost.Test there feels strange. These are general-purpose facilities, not specific to networking.
* I'd add Boost.URL and Boost.JSON (since URLs and JSON are pretty common in networking).

**Comment by PeterTurcan** [comment]
done

**Comment by alandefreitas** [comment]
You can close issues by including the footer `fix #113` in your commit messages.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
https://www.conventionalcommits.org/en/v1.0.0/
