### ISSUE TITLE
Missing points in Organization Requirements

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#142]
**Which documentation does this apply to?**
_(Contributor's Guide)_

I've recently integrated Boost.Redis into Boost. I've been following https://docs.cppalliance.org/contributor-guide/requirements/organization-requirements.html along to help the process (it's almost worked perfectly, so nice job :)). I've noticed a couple missing points though:

* It should mention that a root-level `CMakeLists.txt`, with a certain structure, is required. This is documented [here](https://github.com/boostorg/cmake/blob/develop/developer.md), so there's probably no need to replicate it, but just link to it.
* Almost all new libraries now use a `test/cmake_test` folder with a certain structure. I've noticed this is not documented in the source above (it should be [this point](https://github.com/boostorg/cmake/blob/develop/developer.md#ci-quick-testing), but it's in TBC.
* [Building documentation](https://docs.cppalliance.org/contributor-guide/requirements/organization-requirements.html#_building_documentation) talks about the `boostdoc` target, but not about the `boostrelease` target, which is the one most new libs use. This target is intended for libraries building HTML documentation, and should generate HTML docs and place them under `doc/html`. I don't know the exact details about the interaction of the two - maybe asking Peter or someone more experienced can be useful.
* The [library metadata](https://docs.cppalliance.org/contributor-guide/requirements/library-metadata.html) section says that the `meta/libraries.json` is optional, but the organization requirements section says it's mandatory. It's mandatory.

**Comment by PeterTurcan** [comment]
@anarthal Thanks for the feedback on the Contributor Guide. I will ask pdimov (I assume that is who you meant) about the documentation build process you mention.

**Comment by PeterTurcan** [comment]
Resolved in this PR: https://github.com/cppalliance/site-docs/pull/141
