### ISSUE TITLE
Provide "Modular Boost" section

### ISSUE THREAD

**Issue by akrzemi1** [cppalliance/site-docs#149]
Apart from the old Boost website, Boost used to have a Boost Trac Wiki with a lot of useful information. One of them was "how to start with modular Boost": https://svn.boost.org/trac/boost/wiki/StartModMaint.

This is a request to resurrect that page as part of the new docs.

**Comment by PeterTurcan** [comment]
I can look into porting the pages to the new site.

**Comment by alandefreitas** [comment]
I don't have access to this content but we did include information about modularization in the new getting started section. We talk about boostdep/depinst and vcpkg.

**Comment by akrzemi1** [comment]
Try this one: http://trac.cpp.al/trac/boost/wiki/StartModMaint
It is titled "Getting Started with Modular Boost Library Maintenance" and it tells how to use git for Boost maintainers.

**Comment by alandefreitas** [comment]
Oh... Nice. It's intended for contributors. The getting started guide is for users. Great content.

**Comment by PeterTurcan** [comment]
I assume the task would be to migrate the  "Getting Started with Modular
Boost Library Maintenance" page, and all of the pages it links to. A few of
the links do not appear to go anywhere specific or useful - so will need
updated, though five pages that seem valid are:

*http://trac.cpp.al/trac10/wiki/TortoiseGitLibMaint
<http://trac.cpp.al/trac10/wiki/TortoiseGitLibMaint>*

*http://trac.cpp.al/trac10/wiki/ModBigPicture
<http://trac.cpp.al/trac10/wiki/ModBigPicture>*

*http://trac.cpp.al/trac10/wiki/StartModWorkflow
<http://trac.cpp.al/trac10/wiki/StartModWorkflow>*

*http://trac.cpp.al/trac10/wiki/StartGitHub
<http://trac.cpp.al/trac10/wiki/StartGitHub>*

*http://trac.cpp.al/trac10/wiki/PostCvtMergePoint
<http://trac.cpp.al/trac10/wiki/PostCvtMergePoint>*

These five pages link to further items, but not other wiki pages that would
need to be converted - so the task looks like converting these 6 pages to
ADOC files, and updating some links that are no longer available or
useful.  Perhaps we need a new top level node in the Contributor Guide,
such as "Working with Modular Boost" - or similar.

Does that make sense?

- Peter
