### ISSUE TITLE
Getting started with Linux, installing from source, typos/corrections

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#26]
**Which documentation does this apply to?**
User's Guide

* Steps as are written right now don't allow for copying code, and don't stand out - I'd move them to be code blocks.
* The `wget` command has two extra surrounding backticks that makes the command invalid
* The URL is wrong (https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_82_0.tar.bz2) - should be 1.82 in both parts of the URL
* Do people really use `CPLUS_INCLUDE_PATH` as of today? Seems like a way to get non-reproducible builds. I've learnt this variable is a thing today.

**Comment by PeterTurcan** [comment]
First three issues have been fixed, there is still mention of CPLUS_INCLUDE_PATH in a Linux example, so I assume the variable is still useful.
