### ISSUE TITLE
Use Boost with Linux and the vpckg manager doesn't actually tell you how to use Boost

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#33]
**Which documentation does this apply to?**
User's Guide

`user-guide/use-boost-with-linux-package-manager.html` seems like a guide to install `vcpkg` on Linux. I'd expect this guide to tell me how to install/use Boost, and to mention that individual libraries can be installed separately.

**Comment by alandefreitas** [comment]
Yes. There are multiple ways to install vcpkg too depending on how you organize things. We can just link to vcpkg instructions and let people figure out that part. Or we can, at most, include a couple of commands people can use to install vcpkg and move on to talking about boost.
