### ISSUE TITLE
User guide: usage example of header-only and compiled library

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#34]
I think it may be worth to show how to consume libraries in the "getting started" guide. The old docs did something like this: https://www.boost.org/doc/libs/1_82_0/more/getting_started/unix-variants.html#id23.

I'd say the most popular way of consuming the libraries (at least on Linux) is via CMake, so I'd base the example on that (something really simple, a `main.cpp` and a `CMakeLists.txt`). That can be more useful (and looks more modern) than setting `LD_LIBRARY_PATH` and `CPLUS_INCLUDE_PATH`. I suggest using URL or JSON as the example library, since they don't need much setup (unlike Beast or MySQL), are fast to compile and implement interesting stuff.

Please note that using `vcpkg` or `conan` changes the way libraries are consumed IIRC (requires some additions to the `CMakeLists.txt` if I'm not mistaken) and thus may require separate usage examples.

**Comment by alandefreitas** [comment]
I think vcpkg and conan shouldn't change how libraries are consumed in CMakeLists.txt. It requires some previous set up but CMakeLists.txt should remain the same. At least, this is the goal, and anything that deviates from that should be considered a bug. We can, however, provide some help with that initial set up, which is basically just passing the toolchain file to cmake.

**Comment by anarthal** [comment]
This is completed, I'll open another for what examples to choose.
