### ISSUE TITLE
User guide: introduction to Boost: provide a link to the license

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#35]
We say:
```
Boost is open-source, and available for you to use in any of your projects. It is free, including for commercial projects.
```
Since the Boost Software License is something that (AFAIK) remains constant between libraries, and it's a huge strength of our libs, I think it may be worth stating _which_ license we're using and provide a link to it: https://www.boost.org/users/license.html

**Comment by vinniefalco** [comment]
Yes we definitely need to make the Boost Software License highly visible and prominent (it even deserves its own dedicated page on the website)

**Comment by PeterTurcan** [comment]
Link to the license has been added.
