### ISSUE TITLE
Explanation of website link scheme 

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/site-docs#42]
This is low priority but somewhere we need to explain how the links are formed on the website to libraries. Such as how to link to a develop or master page of a lib, how to link to a libs docs, and how to link to a specific release version of a lib. Example:

https://boost.org/lib/chrono

versus

https://www.boost.org/doc/libs/1_82_0/libs/json

**Comment by PeterTurcan** [comment]
Started researching and writing this, assigning the issue to myself.

**Comment by PeterTurcan** [comment]
Resolved in this PR: https://github.com/cppalliance/site-docs/pull/141
