### ISSUE TITLE
User guide - use Boost with Linux package manager: extra backticks

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#53]
**Which documentation does this apply to?**
_User's Guide_

There are extra backticks around the commands that get copied when you hit the copy button.

**Comment by alandefreitas** [comment]
Where is it?

**Comment by anarthal** [comment]
I've submitted a PR which was quicker than explaining.

**Comment by alandefreitas** [comment]
I believe @PeterTurcan said he also fixed this in another PR. @PeterTurcan, could you confirm if there are differences in these solutions?

**Comment by PeterTurcan** [comment]
@alandefreitas no differences - my changes may have been unnecessary, but the result is the same.

**Comment by alandefreitas** [comment]
It was already fixed then.
