### ISSUE TITLE
./site.sh doesn't regenerate the site if you checkout to something != develop/master

### ISSUE THREAD

**Issue by anarthal** [cppalliance/site-docs#55]
**Which documentation does this apply to?**
_Repo scripts_

* In the cloned repository, switch to a new branch - `git checkout -b bugfix/whatever`
* Modify some files in any of the guides
* Run `./site.sh`
* Generation succeeds, but the content is not updated.

**Comment by alandefreitas** [comment]
I think I fixed this in https://github.com/cppalliance/site-docs/pull/50.

Could you check if that works for you?
